language: python
env:
    - TOXENV=py27-test
    - TOXENV=py27-install
    - TOXENV=py33-test
    - TOXENV=py33-install
    - TOXENV=py34-test
    - TOXENV=py34-install
    - TOXENV=py35-test
    - TOXENV=py35-install
before_install:
    - travis_retry pip install tox
install: true
script:
    - travis_retry tox
