language: python
env:
    - TOXENV=py27-test
    - TOXENV=py27-install
    - TOXENV=py33-test
    - TOXENV=py33-install
    - TOXENV=py34-test
    - TOXENV=py34-install
before_install:
    - travis_retry pip install tox
install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - sudo apt-get install chktex
script:
    - travis_retry tox
